Ebook1/Controllers/Login1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Ebook1.Models;

namespace Ebook1.Controllers
{ 
    
    public class Login1Controller : Controller
    {
        EBook1DbEntities2 db = new EBook1DbEntities2();
        // GET: Login1
        [HttpGet]
        
        public ActionResult LoginG()
        {
            return View();
        }
        [HttpGet]
        public ActionResult LoginK()
        {


            return View();

        }

        [HttpPost]
        public ActionResult LoginK(User formData)
        {
            User users = new User();
            var Email = db.User.Where(x => x.Email == formData.Email).ToList();
        
      
                
                users.Name = formData.Name;
                users.Surname = formData.Surname;
                users.Password = formData.Password;
                users.Email = formData.Email;
                users.IsManager = false;
                users.IsDeleted = false;
                users.DepartmentID = 1;
                db.User.Add(users);
               
               db.SaveChanges();
            

            return RedirectToRoute("LoginG");

        }
        public void AddUserRoles(string EmailUser)
        {

            UserAndRole role = new UserAndRole();
            var user = db.User.FirstOrDefault(x => x.Email == EmailUser);
            role.Role_id = 1;
            role.User_id = user.ID;
            role.Role_name = "Admin";
            db.UserAndRole.Add(role);
            db.SaveChanges();

        }


        [HttpPost]
        public ActionResult LoginG(User user)
        {
            User model = new User();

            model = db.User.FirstOrDefault(x => x.Email == user.Email);
            bool deger = false;
            if (model != null)
            {
                if (model.Password == user.Password)
                {

                    deger = true;



                }

            }

            if (deger == true)
            {
                FormsAuthentication.SetAuthCookie(model.Email, true);
                return RedirectToRoute("Home");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Kullanıcı Bulunamadı . Lütfen Geçerli Bir Kullanıcı Adı ile giriş yapınız.");
                return View();
            }


        }

        public ActionResult Signout()
        {
            FormsAuthentication.SignOut();
            return RedirectToRoute("LoginG");
        }

    }
}

Ebook1/Views/Login1/LoginG.cshtml
@model Ebook1.Models.User

@{
    ViewBag.Title = "LoginG";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V11</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="images/icons/favicon.ico" />
    <!--===============================================================================================-->

    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <!--===============================================================================================-->

    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" />
    <!--===============================================================================================-->

    <link href="~/fonts/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" rel="stylesheet" />
    <!--===============================================================================================-->

    <link href="~/Content/vendor/animate/animate.css" rel="stylesheet" />
    <!--===============================================================================================-->

    <link href="~/Content/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" />

    <!--===============================================================================================-->

    <link href="~/Content/vendor/select2/select2.min.css" rel="stylesheet" />
    <!--===============================================================================================-->

    <link href="~/Content/css/css/util.css" rel="stylesheet" />

    <link href="~/Content/css/css/main.css" rel="stylesheet" />
    <!--===============================================================================================-->
</head>
<body>

    <div class="limiter">
        <div class="container-login100">

            <div class="wrap-login100 p-l-50 p-r-50 p-t-77 p-b-30">
        
                    @ViewBag.Massage
                    @using (Html.BeginForm("LoginG", "Login1", FormMethod.Post))
                    {
                        @Html.ValidationSummary(false, "", new { @class = "text-danger" });

                        <span class="login100-form-title p-b-55">
                            Giriş Yap
                        </span>

                        <div class="wrap-input100 validate-input m-b-16" data-validate="Valid email is required: ex@abc.xyz">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Email)
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                            </div>
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <span class="lnr lnr-envelope"></span>
                            </span>
                        </div>

                        <div class="wrap-input100 validate-input m-b-16" data-validate="Password is required">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Password)
                                @Html.TextBoxFor(m => m.Password, new { @class = "form-control", placeholder = "Şifre" })
                            </div>
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <span class="lnr lnr-lock"></span>
                            </span>
                        </div>


                        <div class="contact100-form-checkbox m-l-4">
                            <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                            <label class="label-checkbox100" for="ckb1">
                                Hatırla
                            </label>
                        </div>

                        <input type="submit" value="Giriş Yap" class="inputButton" />

                        <div class="container-login100-form-btn p-t-25">

                            <a>Hesbaınız yok mu?</a>

                        </div>

                        <div class="text-center w-full p-t-42 p-b-22">
                            <span class="txt1">

                            </span>
                        </div>
                        <div class="container-login100-form-btn p-t-25">

                            <a href="@Url.RouteUrl("LoginK")">Kayıt Ol</a>

                        </div>

                    }


                    <div class="text-center w-full p-t-115">
                        <span class="txt1">

                        </span>

                        <a class="txt1 bo1 hov1" href="#">

                        </a>
                    </div>
                </form>
            </div>

        </div>

    </div>




    <!--===============================================================================================-->
    <script src="~/Content/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->

    <script src="~/Content/vendor/bootstrap/js/popper.js"></script>

    <script src="~/Content/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->

    <script src="~/Content/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->

    <script src="~/Content/js/js/main.js"></script>

</body>
</html>

Ebook1/Views/Login1/LoginK.cshtml
@model Ebook1.Models.User


@{
    ViewBag.Title = "LoginK";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<html lang="en">
<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-l-50 p-r-50 p-t-77 p-b-30">
               
                    <span class="login100-form-title p-b-55">
                        Kayıt Ol
                    </span>
                    @using (Html.BeginForm("LoginK", "Login1", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="wrap-input100 validate-input m-b-16">
                            @Html.LabelFor(m => m.Name)
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">

                            </span>
                        </div>

                        <div class="wrap-input100 validate-input m-b-16">
                            @Html.LabelFor(m => m.Surname)
                            @Html.TextBoxFor(m => m.Surname, new { @class = "form-control", placeholder = "Surname" })
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">

                            </span>
                        </div>

                        <div class="wrap-input100 validate-input m-b-16" data-validate="Valid email is required: ex@abc.xyz">
                            @Html.LabelFor(m => m.Email)
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <span class="lnr lnr-envelope"></span>
                            </span>
                        </div>

                        <div class="wrap-input100 validate-input m-b-16" data-validate="Password is required">
                            @Html.LabelFor(m => m.Password)
                            @Html.TextBoxFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })
                            <span class="focus-input100"></span>
                            <span class="symbol-input100">
                                <span class="lnr lnr-lock"></span>
                            </span>
                        </div>

                        <button type="submit" class="btn btn-success" href="@Url.RouteUrl("LoginG")">Kayıt Ol</button>



                    }

                        <div class="text-center w-full p-t-115">
                            <span class="txt1">

                            </span>

                            <a class="txt1 bo1 hov1" href="#">

                            </a>
                        </div>

              
            </div>


        </div>

    </div>

    <head>
       
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--===============================================================================================-->
        <link rel="icon" type="image/png" href="images/icons/favicon.ico" />
        <!--===============================================================================================-->

        <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
        <!--===============================================================================================-->

        <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" />
        <!--===============================================================================================-->

        <link href="~/fonts/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" rel="stylesheet" />
        <!--===============================================================================================-->

        <link href="~/Content/vendor/animate/animate.css" rel="stylesheet" />
        <!--===============================================================================================-->

        <link href="~/Content/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" />

        <!--===============================================================================================-->

        <link href="~/Content/vendor/select2/select2.min.css" rel="stylesheet" />
        <!--===============================================================================================-->

        <link href="~/Content/css/css/util.css" rel="stylesheet" />

        <link href="~/Content/css/css/main.css" rel="stylesheet" />
        <!--===============================================================================================-->
    </head>


    <!--===============================================================================================-->
    <script src="~/Content/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->

    <script src="~/Content/vendor/bootstrap/js/popper.js"></script>

    <script src="~/Content/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->

    <script src="~/Content/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->

    <script src="~/Content/js/js/main.js"></script>

</body>
</html>