Ebook1/Areas/admin/Controllers/BookEducationController.cs
using Ebook1.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;


using System.Configuration;
using System.Data;


namespace Ebook1.Areas.admin.Controllers
{
    public class BookEducationController : Controller
    {
        EBook1DbEntities2 db = new EBook1DbEntities2();
        // GET: admin/BookEducation
        public ActionResult BookList()
        {
            using (EBook1DbEntities2 db = new EBook1DbEntities2() )
            {

                return View(db.Book.ToList());
            }
        }
        [HttpGet]
        public ActionResult BookAddAdmin()
        {
            using (EBook1DbEntities2 db = new EBook1DbEntities2())
            {
                
                ViewBag.Book = db.Lesson.ToList();
          
                return View();
            }
         
        }



        [HttpPost]
        public ActionResult BookAddAdmin( int LessonID, string BookName, string Comment, double Price, HttpPostedFileBase ImageData)
        {
            EBook1DbEntities2 db = new EBook1DbEntities2();
            Book book = new Book();
      
            
            byte[] bytes;
            if (ImageData != null)
            {
                using (BinaryReader br = new BinaryReader(ImageData.InputStream))
                {
                    bytes = br.ReadBytes(ImageData.ContentLength);
                }
                book.Image = bytes;
            }
            else
            {
                book.Image = null;
            }
            book.LessonID = LessonID;
            book.BookName = BookName;
            book.Comment = Comment;
            book.Price = Price;


    

    
            db.Book.Add(book);
            db.SaveChanges();

           

           
            return RedirectToRoute("BookList");
        }

        //public ActionResult EditBook(int ID)
        //{
        //    using (EBook1DbEntities2 db = new EBook1DbEntities2())
        //    {

        //        ViewBag.Book = db.Lesson.ToList();
        //        Book book = db.Book.SingleOrDefault(x => x.ID.Equals(ID));
        //        if (book != null)
        //        {
        //            return View(book);
        //        }
        //    }
        //    return RedirectToRoute("BookList");
        //}


        //[HttpPost]
        //public ActionResult EditBook(Book model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        using (EBook1DbEntities2 db = new EBook1DbEntities2())
        //        {
        //            db.Entry(model).State = EntityState.Modified;
        //            db.SaveChanges();
        //            ModelState.Clear();

        //        }
        //    }
        //    return View(model);
        //}


        //public ActionResult DeleteSubject(int ID)
        //{
        //    string message = string.Empty;
        //    using (EBook1DbEntities2 db = new EBook1DbEntities2())
        //    {
        //        Book book = db.Book.SingleOrDefault(x => x.ID.Equals(ID));
        //        if (book != null)
        //        {
        //            db.Book.Remove(book);
        //            db.SaveChanges();
        //            message = JsonConvert.SerializeObject(new { durum = "OK", mesaj = "Konu Silindi" });
        //        }
        //        else
        //        {
        //            message = JsonConvert.SerializeObject(new { durum = "No", mesaj = "Konu Silinemedi" });
        //        }
        //    }
        //    return RedirectToRoute("BookList");
        //}
    }

}

Ebook1/Areas/admin/Views/BookEducation/BookAddAdmin.cshtml
@using Ebook1.Models
@model List<Book>


@{
    ViewBag.Title = "BookAddAdmin";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}
<div class="col-md-6 col-sm-6 col-xs-6"
     style="margin: 0 auto;">
    <div class="x_panel">
        <div class="x_title">
            <h2>Kitap Ekle <small></small></h2>

            <div class="clearfix"></div>
        </div>
 


        @Html.Raw(@ViewBag.Message)
        @using (Html.BeginForm("BookAddAdmin", "BookEducation", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="x_content">
                <br />

                <form action="/BookAddAdmin" method="post" enctype="multipart/form-data">



                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="LessonName">
                        Ders Adı <span class="required">:</span>


                    </label>

                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <select id="UserId" name="UserName" class="form-control">
                            @foreach (var item in ViewBag.Book)
                            {
                                <option value="@item.ID">@item.LessonName</option>
                            }

                        </select>
                    </div>


                    <div class="form-group">
                        <label>Kitap Adı</label>
                        <input type="text" name="BookName" class="form-control" />

                    </div>


                    <div class="form-group">
                        <label>Kitap Açıklaması</label>
                        <input type="text" name="Comment" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label>Kitap Fiyatı</label>
                        <input type="text" name="Price" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>Kitap Görseli</label>
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            Resim Ekleyiniz
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="file" name="PostedFile" value="" accept="image/*" />
                        </div>
                    </div>
                    <br /><br />
                    <hr />

                    <br />

                    <button type="submit" class="btn btn-success" href="@Url.RouteUrl("BookAdd1")">Ekle</button>
                </form>
            </div>


            <br />
            <br />
        }
    </div>
     

</div>

Ebook1/Areas/admin/Views/BookEducation/BookList.cshtml
@using Ebook1.Models

@model List <Book>
    @{
    ViewBag.Title = "BookList";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<a class="btn btn-success" href="@Url.RouteUrl("BookAddAdmin")">Yeni Kitap</a>
<h2>
    Kitap  Listesi
</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Ad</th>
            <th>Açıklama</th>
            <th>Fiyat</th>
            <th>Resim</th>
            <th>Güncelle</th>
            <th>Sil</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var Book in Model)
        {
        <tr>
            <td>@Book.ID</td>
            <td>@Book.BookName</td>
            <td>@Book.Comment</td>
            <td>@Book.Price</td>
            <td>@Book.Image</td>
            <td><a class="btn btn-primary" href="@Url.Action("BookAddAdmin", new { Book.ID })">Güncelle </a></td>
            <td><a class="btn btn-primary" href="@Url.Action("DeleteLesson", new { Book.ID })">Sil </a></td>

        </tr>
        }
    </tbody>
</table>

Ebook1/Areas/admin/Views/BookEducation/EditBook.cshtml
@model Ebook1.Models.Book

@{
    ViewBag.Title = "EditBook";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Kitap <small>Kitap İçeriğinin Eklenmesi</small></h2>

            <div class="clearfix"></div>
        </div>


        <div class="clearfix"></div>

        @Html.Raw(@ViewBag.Message)
        @using (Html.BeginForm("EditBook", "BookList", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

    <div class="x_content">
        <br />




        <div class="clearfix"></div>
        <br />
        <div class="form-group">

            @Html.HiddenFor(model => model.ID)
        </div>

        <div class="form-group">
            <label>Kitap Adı</label>
            @Html.EditorFor(model => model.BookName)
            @Html.ValidationMessageFor(model => model.BookName)
        </div>

        <div class="form-group">
            <label>Kitap Açıklaması</label>
            @Html.EditorFor(model => model.Comment)
            @Html.ValidationMessageFor(model => model.Comment)
        </div>
        <div class="form-group">
            <label>Kitap Fiyatı</label>
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>
        <div class="form-group">
            <label>Kitap Resmi</label>
            @Html.EditorFor(model => model.Image)
            @Html.ValidationMessageFor(model => model.Image)
        </div>



        <br />
      
        <div class="col-md-6 col-sm-6 col-xs-12"> <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage"> </div>
        <button type="submit" class="btn btn-success">Ekle</button>

    </div>
        }

        <br />
        <br />
    </div>

</div>